### ISSUE TITLE
Instead of getting content of the `line` register, GetCurrentOp gets index of the `line` in the enum.

### ISSUE THREAD

**Issue by senior-sigan** [narnine/OMSU#2]
`Register::line` as a field of enum automagically casts to int = 3. The compiler should notify us about this, but who cares....

https://github.com/narnine/OMSU/blob/accf2712811162967a65161503b3949879542983/ASM/src/memory.cpp#L3

**Comment by senior-sigan** [comment]
Also. Use instructions.at(line) instead of [line]

**Comment by nazarovnh** [comment]
IOperation *Memory::GetCurrentOp() const { return instructions[GetReg(line)]; }
